### ISSUE TITLE
Cannot purchase the book in my country

### ISSUE THREAD

**Issue by ArmandGrillet** [mixmastamyk/pro_soft_dev#1]
Hi,

I would like to purchase the book on iBooks but it is not available in my country (France).
![image](https://cloud.githubusercontent.com/assets/2117580/16793940/f9745d66-48d4-11e6-9ca6-aedc225699b9.jpeg)

**Comment by mixmastamyk** [comment]
Oh, thank you.  Unfortunately iBooks pulled the book yesterday because I had a link to Amazon in it :(  … it may take me or day or two to fix my tools, republish, and get it approved.  Thanks for your support.

**Comment by ArmandGrillet** [comment]
Great, thanks for your reply!

**Comment by mixmastamyk** [comment]
Hi, you don't have to close it, I could use a reminder.

**Comment by mixmastamyk** [comment]
Hi, so here's the lowdown.  After a few weeks fighting with Apple, I've decided to give up on them and try Gumroad instead.  Would you be interested in trying it?  There you can download an .epub and you should be able to open it on an Apple device and choose "open in ibooks."

The URL is:
    https://gum.co/psdbook

They say they support many countries, so I'm curious how it looks in France?  Thank you.

**Comment by ArmandGrillet** [comment]
Hi, it looks like it works. The only downside is that it is in dollars so there will be a currency conversion during the payment but I can pay. 

I'm not buying it yet (no time to read it now) but thanks for this!

**Comment by mixmastamyk** [comment]
Ok, thanks for looking.
