### ISSUE TITLE
oh my! link in Introduction is dead

### ISSUE THREAD

**Issue by evelynmitchell** [mixmastamyk/pro_soft_dev#2]
(oh my! ) https://www.youtube.com/watch?v=Etx-nDCZzLo
The content is no longer available.

**Comment by mixmastamyk** [comment]
Why, thank you.  Might take me a few days to fix, because we don't have solid network at home yet.

**Comment by mixmastamyk** [comment]
Ok, internet at home and link fixed, thx again.
